% Solve a Clustering Problem with a Self-Organizing Map
% Script generated by Neural Clustering app
% Created 07-Jun-2019 12:36:08
%
% This script assumes these variables are defined:
%
%   SMall - input data.
% 
% The SMall variable is extracted from file 'SM_all.csv'.

x = SMall;

% Create a Self-Organizing Map
dimension1 = 10;
dimension2 = 10;
net = selforgmap([dimension1 dimension2]);

% Train the Network
net.trainParam.epochs = 500;
[net,tr] = train(net,x);

% Test the Network
y = net(x);

% View the Network
view(net)

% Plots
% Uncomment these lines to enable various plots.
%figure, plotsomtop(net)
%figure, plotsomnc(net)
figure, plotsomnd(net)
%figure, plotsomplanes(net)
figure, plotsomhits(net,x)
%figure, plotsompos(net,x)

%Export matrix with SOM output
csvwrite('SOM_matrix.csv',y)

% Create the RGB matrix (colors) using number of dataset hits per cell
total = sum(y,2);
D = sum(y(:,1:285),2);
NC = sum(y(:,286:345),2);
M = sum(y(:,346:366),2);
colors = [D./total,NC./total,M./total];
colors(isnan(colors))=0;

% SOM plot coloured by dataset
xhex=[1 2 3 3 2 1]; % x-coordinates of the vertices
yhex=[2 3 2 1 0 1]; % y-coordinates of the vertices
n = 0
for i=2:dimension1+1;
    j=i-1;
    for k=2:dimension2+1;
        m=k-1;
        n = n+1;
        patch((xhex+mod(i,-2))+2*m,yhex+2*j,[1-(colors(n,1)) 1-(colors(n,2)) 1-(colors(n,3))] ) % make a hexagon at [2i,2j]
        hold on
    end
end


% Create legend for the previous plot 
xy=[0 0; 1 0; 0.5 sqrt(3)/2];
col=[1 0 0; 0 1 0; 0 0 1];
patch('Vertices',xy, 'Faces',[1:size(xy,1)], 'EdgeColor','none','FaceVertexCData', 1-col,'FaceColor','interp');
axis off
text(xy(1,1), xy(1,2)-0.05,'Drugs','HorizontalAlignment', 'center')
text(xy(2,1), xy(2,2)-0.05,'Natural compounds','HorizontalAlignment', 'center')
text(xy(3,1), xy(3,2)+0.05,'Metabolites','HorizontalAlignment', 'center')